-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.app_admins (
  user_id uuid NOT NULL UNIQUE,
  CONSTRAINT app_admins_pkey PRIMARY KEY (user_id),
  CONSTRAINT app_admins_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.claim_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  consultant_id uuid NOT NULL,
  first_name text,
  last_name text,
  contact_email text,
  request_ip inet,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT claim_requests_pkey PRIMARY KEY (id),
  CONSTRAINT claim_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT claim_requests_consultant_id_fkey FOREIGN KEY (consultant_id) REFERENCES public.consultants(id)
);
CREATE TABLE public.consultant_contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  consultant_id uuid NOT NULL,
  sender_user_id uuid NOT NULL,
  subject text NOT NULL,
  message text NOT NULL,
  name text,
  email text NOT NULL,
  phone text,
  location text,
  budget text,
  job_id uuid,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'sent'::text, 'delivered'::text, 'failed'::text, 'bounced'::text, 'opened'::text, 'replied'::text])),
  delivery_provider text,
  delivery_message_id text,
  delivered_at timestamp with time zone,
  source text,
  referrer text,
  utm jsonb NOT NULL DEFAULT '{}'::jsonb,
  meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT consultant_contacts_pkey PRIMARY KEY (id),
  CONSTRAINT consultant_contacts_consultant_id_fkey FOREIGN KEY (consultant_id) REFERENCES public.consultants(id),
  CONSTRAINT consultant_contacts_sender_user_id_fkey FOREIGN KEY (sender_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.consultant_favourites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  consultant_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT consultant_favourites_pkey PRIMARY KEY (id),
  CONSTRAINT consultant_favourites_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT consultant_favourites_consultant_id_fkey FOREIGN KEY (consultant_id) REFERENCES public.consultants(id)
);
CREATE TABLE public.consultant_page_views (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  consultant_id uuid NOT NULL,
  viewer_id uuid,
  anon_hash text,
  user_agent text,
  viewed_at timestamp with time zone NOT NULL DEFAULT now(),
  source text,
  CONSTRAINT consultant_page_views_pkey PRIMARY KEY (id),
  CONSTRAINT consultant_page_views_consultant_id_fkey FOREIGN KEY (consultant_id) REFERENCES public.consultants(id),
  CONSTRAINT consultant_page_views_viewer_id_fkey FOREIGN KEY (viewer_id) REFERENCES auth.users(id)
);
CREATE TABLE public.consultant_portfolio (
  consultant_id uuid NOT NULL,
  overall_intro text CHECK (overall_intro IS NULL OR char_length(overall_intro) <= 1200),
  images jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(images) = 'array'::text),
  attachment jsonb,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  links jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(links) = 'array'::text AND jsonb_array_length(links) <= 3),
  CONSTRAINT consultant_portfolio_pkey PRIMARY KEY (consultant_id),
  CONSTRAINT consultant_portfolio_consultant_id_fkey FOREIGN KEY (consultant_id) REFERENCES public.consultants(id)
);
CREATE TABLE public.consultant_services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  consultant_id uuid,
  service_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT consultant_services_pkey PRIMARY KEY (id),
  CONSTRAINT consultant_services_consultant_id_fkey FOREIGN KEY (consultant_id) REFERENCES public.consultants(id),
  CONSTRAINT consultant_services_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.consultants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  display_name text,
  headline text,
  bio text,
  company text,
  location text,
  contact_email text,
  phone text,
  visibility text DEFAULT 'public'::text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  place_id text UNIQUE,
  slug text,
  claimed_at timestamp with time zone,
  claimed_by uuid,
  claim_token text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  reviewer_notes text,
  linkedin_url text CHECK (linkedin_url IS NULL OR char_length(linkedin_url) <= 2048 AND linkedin_url ~* '^https://([a-z0-9-]+\.)*linkedin\.com/.*$'::text),
  facebook_url text CHECK (facebook_url IS NULL OR char_length(facebook_url) <= 2048 AND facebook_url ~* '^https://([a-z0-9-]+\.)*facebook\.com/.*$'::text),
  twitter_url text CHECK (twitter_url IS NULL OR char_length(twitter_url) <= 2048 AND twitter_url ~* '^https://([a-z0-9-]+\.)*(twitter\.com|x\.com)/.*$'::text),
  instagram_url text CHECK (instagram_url IS NULL OR char_length(instagram_url) <= 2048 AND instagram_url ~* '^https://([a-z0-9-]+\.)*instagram\.com/.*$'::text),
  abn text,
  acn text,
  abn_verified boolean NOT NULL DEFAULT false,
  abn_status text,
  abn_entity_name text,
  abn_entity_type text,
  abn_gst_registered_from date,
  abn_last_checked timestamp with time zone,
  abn_data jsonb,
  view_count bigint NOT NULL DEFAULT 0,
  is_trainer boolean NOT NULL DEFAULT false,
  provider_kind USER-DEFINED NOT NULL DEFAULT 'both'::consultant_kind,
  invite_email boolean NOT NULL DEFAULT false,
  CONSTRAINT consultants_pkey PRIMARY KEY (id),
  CONSTRAINT consultants_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT consultants_claimed_by_fkey FOREIGN KEY (claimed_by) REFERENCES auth.users(id),
  CONSTRAINT consultants_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.email_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recipient text NOT NULL,
  subject text NOT NULL,
  email_type text NOT NULL,
  related_id uuid,
  status text NOT NULL DEFAULT 'pending'::text,
  error_message text,
  sent_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT email_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.event_submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  submitted_by uuid NOT NULL,
  title text NOT NULL CHECK (char_length(title) <= 200),
  summary text NOT NULL CHECK (summary IS NULL OR char_length(summary) <= 300),
  description text NOT NULL CHECK (description IS NULL OR char_length(description) <= 5000),
  starts_at timestamp with time zone NOT NULL,
  ends_at timestamp with time zone NOT NULL,
  timezone text,
  delivery_method text NOT NULL DEFAULT 'in_person'::text CHECK (delivery_method = ANY (ARRAY['in_person'::text, 'online'::text, 'hybrid'::text])),
  location_name text,
  address_line1 text,
  address_line2 text,
  suburb text,
  state text,
  postcode text,
  country text DEFAULT 'AU'::text,
  place_id text,
  join_url text CHECK (join_url IS NULL OR char_length(join_url) <= 2048 AND join_url ~* '^https?://'::text),
  external_url text CHECK (external_url IS NULL OR char_length(external_url) <= 2048 AND external_url ~* '^https?://'::text),
  organizer_name text CHECK (organizer_name IS NULL OR char_length(organizer_name) <= 200),
  organizer_url text CHECK (organizer_url IS NULL OR char_length(organizer_url) <= 2048 AND organizer_url ~* '^https?://'::text),
  tags ARRAY NOT NULL DEFAULT '{}'::text[],
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'denied'::text])),
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  review_notes text,
  event_id uuid,
  request_ip inet,
  user_agent text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  consultant_id uuid,
  CONSTRAINT event_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT event_submissions_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES auth.users(id),
  CONSTRAINT event_submissions_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id),
  CONSTRAINT event_submissions_consultant_id_fkey FOREIGN KEY (consultant_id) REFERENCES public.consultants(id),
  CONSTRAINT event_submissions_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by uuid,
  title text NOT NULL CHECK (char_length(title) <= 200),
  summary text NOT NULL CHECK (summary IS NULL OR char_length(summary) <= 300),
  description text NOT NULL CHECK (description IS NULL OR char_length(description) <= 5000),
  starts_at timestamp with time zone NOT NULL,
  ends_at timestamp with time zone NOT NULL,
  timezone text,
  delivery_method text NOT NULL DEFAULT 'in_person'::text CHECK (delivery_method = ANY (ARRAY['in_person'::text, 'online'::text, 'hybrid'::text])),
  location_name text,
  address_line1 text,
  address_line2 text,
  suburb text,
  state text,
  postcode text,
  country text DEFAULT 'AU'::text,
  place_id text,
  join_url text CHECK (join_url IS NULL OR char_length(join_url) <= 2048 AND join_url ~* '^https?://'::text),
  external_url text CHECK (external_url IS NULL OR char_length(external_url) <= 2048 AND external_url ~* '^https?://'::text),
  organizer_name text CHECK (organizer_name IS NULL OR char_length(organizer_name) <= 200),
  organizer_url text CHECK (organizer_url IS NULL OR char_length(organizer_url) <= 2048 AND organizer_url ~* '^https?://'::text),
  tags ARRAY NOT NULL DEFAULT '{}'::text[],
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'archived'::text, 'cancelled'::text])),
  cancel_reason text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT events_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT events_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.favorites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  consultant_id uuid,
  listing_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT favorites_pkey PRIMARY KEY (id),
  CONSTRAINT favorites_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT favorites_consultant_id_fkey FOREIGN KEY (consultant_id) REFERENCES public.consultants(id),
  CONSTRAINT favorites_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES public.listings(id)
);
CREATE TABLE public.job_category_subscriptions (
  id bigint NOT NULL DEFAULT nextval('job_category_subscriptions_id_seq'::regclass),
  user_id uuid NOT NULL,
  category_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  paused boolean NOT NULL DEFAULT false,
  CONSTRAINT job_category_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT job_category_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT job_category_subscriptions_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.service_categories(id)
);
CREATE TABLE public.job_notification_log (
  id bigint NOT NULL DEFAULT nextval('job_notification_log_id_seq'::regclass),
  job_id uuid NOT NULL,
  user_id uuid NOT NULL,
  category_id uuid NOT NULL,
  sent_at timestamp with time zone NOT NULL DEFAULT now(),
  delivery_status text NOT NULL DEFAULT 'queued'::text,
  message_id text,
  CONSTRAINT job_notification_log_pkey PRIMARY KEY (id),
  CONSTRAINT job_notification_log_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT job_notification_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT job_notification_log_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.service_categories(id)
);
CREATE TABLE public.jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  title text NOT NULL,
  company text,
  location text,
  budget text,
  close_date date NOT NULL,
  description text,
  contact_name text,
  contact_email text,
  service_id uuid,
  recipient_ids ARRAY NOT NULL DEFAULT '{}'::uuid[],
  email_log jsonb NOT NULL DEFAULT '[]'::jsonb,
  preferred_payment_type text CHECK (preferred_payment_type IS NULL OR (preferred_payment_type = ANY (ARRAY['Ongoing Hourly'::text, 'Fixed-Term Hourly'::text, 'Fixed Budget'::text, 'Cost Plus'::text]))),
  urgency text CHECK (urgency IS NULL OR (urgency = ANY (ARRAY['Immediately'::text, 'Within Weeks'::text, 'Within Months'::text, 'Exploring Options'::text]))),
  listing_type text CHECK (listing_type IS NULL OR (listing_type = ANY (ARRAY['Public'::text, 'Both'::text, 'Private'::text]))),
  category_id uuid,
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'closed'::text, 'deleted'::text, 'paused'::text])),
  CONSTRAINT jobs_pkey PRIMARY KEY (id),
  CONSTRAINT jobs_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT jobs_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT jobs_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.service_categories(id)
);
CREATE TABLE public.listings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  title text NOT NULL,
  short_description text,
  services jsonb DEFAULT '[]'::jsonb,
  contact jsonb DEFAULT '{}'::jsonb,
  hero_image text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  description text,
  location text,
  status text DEFAULT 'active'::text,
  job_type USER-DEFINED NOT NULL DEFAULT 'general'::listing_job_type,
  CONSTRAINT listings_pkey PRIMARY KEY (id),
  CONSTRAINT listings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text UNIQUE,
  description text,
  website text,
  contact_email text,
  owner uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id),
  CONSTRAINT organizations_owner_fkey FOREIGN KEY (owner) REFERENCES auth.users(id)
);
CREATE TABLE public.portfolios (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  consultant_id uuid,
  title text NOT NULL,
  description text,
  media_urls ARRAY,
  links ARRAY,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT portfolios_pkey PRIMARY KEY (id),
  CONSTRAINT portfolios_consultant_id_fkey FOREIGN KEY (consultant_id) REFERENCES public.consultants(id)
);
CREATE TABLE public.profile_views (
  id bigint NOT NULL DEFAULT nextval('profile_views_id_seq'::regclass),
  consultant_id uuid,
  viewer_id uuid,
  source text,
  viewed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profile_views_pkey PRIMARY KEY (id),
  CONSTRAINT profile_views_consultant_id_fkey FOREIGN KEY (consultant_id) REFERENCES public.consultants(id),
  CONSTRAINT profile_views_viewer_id_fkey FOREIGN KEY (viewer_id) REFERENCES auth.users(id)
);
CREATE TABLE public.role_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  position integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  group_name text,
  group_slug text CHECK (group_slug IS NULL OR group_slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'::text),
  group_position integer NOT NULL DEFAULT 0,
  CONSTRAINT role_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.service_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  name text NOT NULL UNIQUE,
  description text,
  position integer DEFAULT 0,
  CONSTRAINT service_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text UNIQUE,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  category_id uuid,
  position integer DEFAULT 0,
  CONSTRAINT services_pkey PRIMARY KEY (id),
  CONSTRAINT services_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.service_categories(id)
);
CREATE TABLE public.training_courses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  consultant_id uuid NOT NULL,
  title text NOT NULL,
  slug text,
  summary text,
  description text,
  category text,
  tags ARRAY NOT NULL DEFAULT '{}'::text[],
  level text,
  duration_hours numeric,
  delivery_default text CHECK (delivery_default IS NULL OR (delivery_default = ANY (ARRAY['in_person'::text, 'online'::text, 'hybrid'::text]))),
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'archived'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT training_courses_pkey PRIMARY KEY (id),
  CONSTRAINT training_courses_consultant_id_fkey FOREIGN KEY (consultant_id) REFERENCES public.consultants(id)
);
CREATE TABLE public.training_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  course_id uuid NOT NULL,
  starts_at timestamp with time zone NOT NULL,
  ends_at timestamp with time zone NOT NULL,
  timezone text,
  delivery_method text NOT NULL DEFAULT 'in_person'::text CHECK (delivery_method = ANY (ARRAY['in_person'::text, 'online'::text, 'hybrid'::text])),
  location_name text,
  address_line1 text,
  address_line2 text,
  suburb text,
  state text,
  postcode text,
  country text DEFAULT 'AU'::text,
  place_id text,
  join_url text,
  bookings_enabled boolean NOT NULL DEFAULT false,
  availability_display text NOT NULL DEFAULT 'remaining_places'::text CHECK (availability_display = ANY (ARRAY['remaining_places'::text, 'availability_only'::text])),
  booking_url text CHECK (booking_url IS NULL OR char_length(booking_url) <= 2048 AND booking_url ~* '^https?://'::text),
  capacity integer CHECK (capacity IS NULL OR capacity >= 0),
  price_cents integer CHECK (price_cents IS NULL OR price_cents >= 0),
  currency text NOT NULL DEFAULT 'AUD'::text,
  gst_included boolean NOT NULL DEFAULT true,
  status text NOT NULL DEFAULT 'scheduled'::text,
  cancel_reason text,
  notes text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT training_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT training_sessions_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.training_courses(id)
);
CREATE TABLE public.training_session_bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  user_id uuid NOT NULL,
  booking_name text NOT NULL CHECK (char_length(trim(booking_name)) >= 1 AND char_length(trim(booking_name)) <= 120),
  booking_email text NOT NULL CHECK (char_length(trim(booking_email)) >= 3 AND char_length(trim(booking_email)) <= 320),
  booking_phone text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'cancelled'::text, 'waitlisted'::text])),
  notes text,
  booked_at timestamp with time zone NOT NULL DEFAULT now(),
  cancelled_at timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT training_session_bookings_pkey PRIMARY KEY (id),
  CONSTRAINT training_session_bookings_session_user_key UNIQUE (session_id, user_id),
  CONSTRAINT training_session_bookings_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.training_sessions(id),
  CONSTRAINT training_session_bookings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL,
  user_type text DEFAULT 'unspecified'::text CHECK (user_type = ANY (ARRAY['unspecified'::text, 'consultant'::text, 'client'::text, 'both'::text])),
  organisation_size text NOT NULL DEFAULT 'unspecified'::text CHECK (organisation_size = ANY (ARRAY['unspecified'::text, 'individual'::text, '1-8'::text, '8-25'::text, '26-100'::text, '101+'::text])),
  organisation_name text,
  profession text NOT NULL DEFAULT 'unspecified'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  first_name text,
  last_name text,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.worker_availability (
  worker_id uuid NOT NULL,
  available_now boolean NOT NULL DEFAULT false,
  available_from date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT worker_availability_pkey PRIMARY KEY (worker_id),
  CONSTRAINT worker_availability_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES public.workers(id)
);
CREATE TABLE public.worker_experiences (
  id bigint NOT NULL DEFAULT nextval('worker_experiences_id_seq'::regclass),
  worker_id uuid NOT NULL,
  role_title text NOT NULL,
  company text,
  description text,
  location text,
  start_date date,
  end_date date,
  is_current boolean NOT NULL DEFAULT false,
  achievements jsonb,
  position integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT worker_experiences_pkey PRIMARY KEY (id),
  CONSTRAINT worker_experiences_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES public.workers(id)
);
CREATE TABLE public.worker_roles (
  worker_id uuid NOT NULL,
  role_category_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT worker_roles_pkey PRIMARY KEY (worker_id, role_category_id),
  CONSTRAINT worker_roles_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES public.workers(id),
  CONSTRAINT worker_roles_role_category_id_fkey FOREIGN KEY (role_category_id) REFERENCES public.role_categories(id)
);
CREATE TABLE public.workers (
  id uuid NOT NULL,
  display_name text,
  headline text,
  bio text,
  location text,
  visibility text NOT NULL DEFAULT 'public'::text CHECK (visibility = ANY (ARRAY['public'::text, 'private'::text])),
  status text NOT NULL DEFAULT 'approved'::text CHECK (status = ANY (ARRAY['approved'::text, 'pending'::text, 'rejected'::text, 'draft'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  working_rights_slug text,
  public_profile_name text,
  CONSTRAINT workers_pkey PRIMARY KEY (id),
  CONSTRAINT workers_id_fkey FOREIGN KEY (id) REFERENCES public.user_profiles(id),
  CONSTRAINT workers_working_rights_slug_fkey FOREIGN KEY (working_rights_slug) REFERENCES public.working_rights_categories(slug)
);
CREATE TABLE public.working_rights_categories (
  id bigint NOT NULL DEFAULT nextval('working_rights_categories_id_seq'::regclass),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  position integer NOT NULL DEFAULT 0,
  CONSTRAINT working_rights_categories_pkey PRIMARY KEY (id)
);